var graphcolor = [
  "#c23531",
  "#2f4554",
  "#61a0a8",
  "#d48265",
  "#91c7ae",
  "#749f83",
  "#ca8622",
  "#bda29a",
  "#6e7074",
  "#546570",
  "#c4ccd3",
];
var graph = {
  color: graphcolor,
  nodes: [
    {
      color: graphcolor[0],
      label: "Ethereum",
      attributes: {},
      y: 404.26147,
      x: -739.36383,
      id: "Ethereum",
      size: 4.7252817,
    },
    {
      color: graphcolor[1],
      label: "Fantom",
      attributes: {},
      y: 862.7517,
      x: -134.2215,
      id: "Fantom",
      size: 6.1554675,
    },
    {
      color: graphcolor[2],
      label: "Arbitrum",
      attributes: {},
      y: 734.4221,
      x: -75.53079,
      id: "Arbitrum",
      size: 100,
    },
    {
      color: graphcolor[3],
      label: "Celo",
      attributes: {},
      y: -624.50604,
      x: -818.97516,
      id: "Celo",
      size: 0.67816025,
    },
    {
      color: graphcolor[4],
      label: "Polygon",
      attributes: {},
      y: -120.37976,
      x: -710.59204,
      id: "Polygon",
      size: 19.818306,
    },
    {
      color: graphcolor[5],
      label: "Bsc",
      attributes: {},
      y: 612.5541,
      x: 71.52897,
      id: "Bsc",
      size: 4.0862627,
    },
    {
      color: graphcolor[6],
      label: "Avalanche",
      attributes: {},
      y: 556.3107,
      x: 1202.1166,
      id: "Avalanche",
      size: 2.3822114,
    },
    {
      color: graphcolor[7],
      label: "Moonbeam",
      attributes: {},
      y: -378.15536,
      x: -1150.2018,
      id: "Moonbeam",
      size: 10.81118,
    },
    {
      color: graphcolor[8],
      label: "Binance",
      attributes: {},
      y: -477.03778,
      x: -127.03764,
      id: "Binance",
      size: 0.40429485,
    },
  ],
  edges: [
    {
      sourceID: "Ethereum",
      attributes: {
        sourceID: "jquery",
        attributes: {},
        targetID: "jsdom",
        size: 1,
      },
      targetID: "Fantom",
      size: 166159.968014,
    },
    {
      sourceID: "Arbitrum",
      attributes: {
        sourceID: "jquery",
        attributes: {},
        targetID: "xmlhttprequest",
        size: 1,
      },
      targetID: "Celo",
      size: 1492.608052,
    },
    {
      sourceID: "Arbitrum",
      attributes: {
        sourceID: "jquery",
        attributes: {},
        targetID: "htmlparser",
        size: 1,
      },
      targetID: "Fantom",
      size: 114559.605954,
    },
    {
      sourceID: "Arbitrum",
      attributes: {
        sourceID: "jquery",
        attributes: {},
        targetID: "contextify",
        size: 1,
      },
      targetID: "Polygon",
      size: 45647.878082,
    },
    {
      sourceID: "Polygon",
      attributes: {
        sourceID: "backbone",
        attributes: {},
        targetID: "underscore",
        size: 1,
      },
      targetID: "Ethereum",
      size: 65302.291368,
    },
    {
      sourceID: "Bsc",
      attributes: {
        sourceID: "faye",
        attributes: {},
        targetID: "faye-websocket",
        size: 1,
      },
      targetID: "Fantom",
      size: 52691.697471,
    },
    {
      sourceID: "Polygon",
      attributes: {
        sourceID: "faye",
        attributes: {},
        targetID: "cookiejar",
        size: 1,
      },
      targetID: "Polygon",
      size: 29.354319,
    },
    {
      sourceID: "Arbitrum",
      attributes: {
        sourceID: "socket.io",
        attributes: {},
        targetID: "redis",
        size: 1,
      },
      targetID: "Avalanche",
      size: 19617.429805,
    },
    {
      sourceID: "Bsc",
      attributes: {
        sourceID: "socket.io",
        attributes: {},
        targetID: "socket.io-client",
        size: 1,
      },
      targetID: "Arbitrum",
      size: 42856.979734,
    },
    {
      sourceID: "Avalanche",
      attributes: {
        sourceID: "mongoose",
        attributes: {},
        targetID: "mongodb",
        size: 1,
      },
      targetID: "Moonbeam",
      size: 123638.520066,
    },
    {
      sourceID: "Ethereum",
      attributes: {
        sourceID: "mongoose",
        attributes: {},
        targetID: "hooks",
        size: 1,
      },
      targetID: "Moonbeam",
      size: 289104.502411,
    },
    {
      sourceID: "Arbitrum",
      attributes: {
        sourceID: "mongoose",
        attributes: {},
        targetID: "ms",
        size: 1,
      },
      targetID: "Ethereum",
      size: 86200.38475,
    },
    {
      sourceID: "Bsc",
      attributes: {
        sourceID: "cheerio",
        attributes: {},
        targetID: "underscore",
        size: 1,
      },
      targetID: "Moonbeam",
      size: 214468.76817,
    },
    {
      sourceID: "Avalanche",
      attributes: {
        sourceID: "cheerio",
        attributes: {},
        targetID: "htmlparser2",
        size: 1,
      },
      targetID: "Fantom",
      size: 169029.093766,
    },
    {
      sourceID: "Avalanche",
      attributes: {
        sourceID: "cheerio",
        attributes: {},
        targetID: "entities",
        size: 1,
      },
      targetID: "Avalanche",
      size: 20,
    },
    {
      sourceID: "Arbitrum",
      attributes: {
        sourceID: "express",
        attributes: {},
        targetID: "mkdirp",
        size: 1,
      },
      targetID: "Arbitrum",
      size: 22.158685,
    },
    {
      sourceID: "Arbitrum",
      attributes: {
        sourceID: "express",
        attributes: {},
        targetID: "connect",
        size: 1,
      },
      targetID: "Binance",
      size: 17614.172686,
    },
    {
      sourceID: "Polygon",
      attributes: {
        sourceID: "express",
        attributes: {},
        targetID: "commander",
        size: 1,
      },
      targetID: "Fantom",
      size: 118682.84633,
    },
    {
      sourceID: "Ethereum",
      attributes: {
        sourceID: "express",
        attributes: {},
        targetID: "debug",
        size: 1,
      },
      targetID: "Binance",
      size: 16061.719748,
    },
    {
      sourceID: "Bsc",
      attributes: {
        sourceID: "express",
        attributes: {},
        targetID: "cookie",
        size: 1,
      },
      targetID: "Polygon",
      size: 179612.15213,
    },
    {
      sourceID: "Polygon",
      attributes: {
        sourceID: "express",
        attributes: {},
        targetID: "send",
        size: 1,
      },
      targetID: "Arbitrum",
      size: 141964.852728,
    },
    {
      sourceID: "Avalanche",
      attributes: {
        sourceID: "express",
        attributes: {},
        targetID: "methods",
        size: 1,
      },
      targetID: "Binance",
      size: 76992.267366,
    },
    {
      sourceID: "Polygon",
      attributes: {
        sourceID: "express",
        attributes: {},
        targetID: "buffer-crc32",
        size: 1,
      },
      targetID: "Moonbeam",
      size: 238555.000298,
    },
    {
      sourceID: "Avalanche",
      attributes: {
        sourceID: "express",
        attributes: {},
        targetID: "fresh",
        size: 1,
      },
      targetID: "Celo",
      size: 3345.288438,
    },
    {
      sourceID: "Bsc",
      attributes: {
        sourceID: "connect",
        attributes: {},
        targetID: "bytes",
        size: 1,
      },
      targetID: "Ethereum",
      size: 125367.294589,
    },
    {
      sourceID: "Polygon",
      attributes: {
        sourceID: "connect",
        attributes: {},
        targetID: "debug",
        size: 1,
      },
      targetID: "Binance",
      size: 86722.802391,
    },
    {
      sourceID: "Bsc",
      attributes: {
        sourceID: "connect",
        attributes: {},
        targetID: "qs",
        size: 1,
      },
      targetID: "Celo",
      size: 9155.909969,
    },
    {
      sourceID: "Ethereum",
      attributes: {
        sourceID: "connect",
        attributes: {},
        targetID: "cookie",
        size: 1,
      },
      targetID: "Polygon",
      size: 43649.621755,
    },
    {
      sourceID: "Ethereum",
      attributes: {
        sourceID: "connect",
        attributes: {},
        targetID: "send",
        size: 1,
      },
      targetID: "Arbitrum",
      size: 226801.226794,
    },
    {
      sourceID: "Ethereum",
      attributes: {
        sourceID: "connect",
        attributes: {},
        targetID: "formidable",
        size: 1,
      },
      targetID: "Avalanche",
      size: 30989.798554,
    },
    {
      sourceID: "Arbitrum",
      attributes: {
        sourceID: "connect",
        attributes: {},
        targetID: "methods",
        size: 1,
      },
      targetID: "Moonbeam",
      size: 84923.426037,
    },
    {
      sourceID: "Ethereum",
      attributes: {
        sourceID: "connect",
        attributes: {},
        targetID: "buffer-crc32",
        size: 1,
      },
      targetID: "Celo",
      size: 481.259063,
    },
    {
      sourceID: "Bsc",
      attributes: {
        sourceID: "connect",
        attributes: {},
        targetID: "fresh",
        size: 1,
      },
      targetID: "Avalanche",
      size: 16858.279935,
    },
    {
      sourceID: "Avalanche",
      attributes: {
        sourceID: "connect",
        attributes: {},
        targetID: "pause",
        size: 1,
      },
      targetID: "Arbitrum",
      size: 24194.752271,
    },
    {
      sourceID: "Avalanche",
      attributes: {
        sourceID: "temp",
        attributes: {},
        targetID: "rimraf",
        size: 1,
      },
      targetID: "Polygon",
      size: 92236.390981,
    },
    {
      sourceID: "Avalanche",
      attributes: {
        sourceID: "request",
        attributes: {},
        targetID: "node-uuid",
        size: 1,
      },
      targetID: "Ethereum",
      size: 10285.297231,
    },
    {
      sourceID: "Polygon",
      attributes: {
        sourceID: "request",
        attributes: {},
        targetID: "mime",
        size: 1,
      },
      targetID: "Celo",
      size: 79655.290077,
    },
    {
      sourceID: "Polygon",
      attributes: {
        sourceID: "request",
        attributes: {},
        targetID: "qs",
        size: 1,
      },
      targetID: "Avalanche",
      size: 69368.28938,
    },
  ],
};
